name: Build_Atlassian_SDK

on: 
  workflow_dispatch:

jobs:
  Build:
          name: Build atlassian sdk from docker file
          runs-on: ubuntu-latest
          steps:
           - name: Set up QEMU
             uses: docker/setup-qemu-action@v1
            
           - name: Set up Docker Buildx
             uses: docker/setup-buildx-action@v1
             
           - name: Login to GitHub Container Registry
             uses: docker/login-action@v1 
             with:
              registry: ghcr.io
              username: ${{ github.repository_owner }}
              password: ${{ secrets.GIT_TOKEN }}
          
           - name: Login to DockerHub
             uses: docker/login-action@v1 
             with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
 
           - 
             name: Build and push
             uses: docker/build-push-action@v2
             with:
              context: .
              platforms: linux/amd64,linux/arm64
              push: true
              tags: |
                sudheerforu/atlassiansdk:latest
                sudheerforu/atlassiansdk:1.0.0
                ghcr.io/sudh33r/atlassiansdk:latest
                ghcr.io/sudh33r/atlassiansdk:1.0.0
